### ISSUE TITLE
Some Locales are not Outputting Correclty

### ISSUE THREAD

**Issue by mchadwickchennault** [mchadwickchennault/CourseCatalog#6]
The locales en-GB, my-MY, and so-SO are not outputting correctly. It looks like they are trying to output as observation catalogs instead of course catalogs. See the "UK" and "UK Sales" catalogs as examples.

**Comment by drmacro** [comment]
Investigating

**Comment by drmacro** [comment]
Cannot reproduce failure with data set I have.

Have removed all code that might possibly generate observations except the unused function lms:get-observation-descriptors()

**Comment by drmacro** [comment]
Also, compared my result using currently-deployed code and my update to remove all observation generation and the results were identical.
